### PR TITLE
Add generators for helix 2D test graphs

### PR DESCRIPTION
**Pull request by dehann**
cc @pvazteixeira new generators for Helix 2D graphs (approximate version for the time being)

XY on top, and yaw angle on bottom figure

Screenshot from 2021-06-09 14-43-14

### CODE REVIEW

**Comment by pvazteixeira** [comment]
this looks great!

**Comment by dehann** [comment]
see:
```julia
fg = generateCanonicalFG_Helix2D!(28)
```

**Comment by dehann** [comment]
okay, fixed to a more general helix generator method.  Still todo while im here:
- [ ] More general interface for x(t) and y(t) "spinal curve",
- [ ] wrapper for `generateCanonicalFG_HelixSkewed2D!`
- [ ] wrapper for `generateCanonicalFG_HelixSineRose2D!`

**Comment by dehann** [comment]
Okay latest and greatest, this should be good to go for now:
Screenshot from 2021-06-11 18-25-30

**Pull request merged**
