### PR TITLE
upgrade BearingRange to use Manifolds.jl

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by Affie** [comment]
This causes more errors in the tests:
Broken Testset for RoME summary: 
  Pass:297
  Broken:1
  Fail:13
  Error:36

It also looks like test takes a longer to run

**Review by Affie — COMMENTED** [review]
The bearing range tests no longer passes

**Comment by dehann** [comment]
likely the surrounding code and tests need to be updated to the new format as per #465.  This factor residual function previously did not meet the new requirements from #465 -- it still assumed measurements were in coordinates.  The new version works with the generators...

The only real change i made was that measurement now comes in as a tangent, and also use the Manifolds.jl plumbing for the mechanics.

**Comment by dehann** [comment]
just looked at it again and there might be a bug in delta theta not calculati the angle in the correct reference frame

**Pull request merged**
