### PR TITLE
Fix testParametricSimulated for Manifolds

### PR DESCRIPTION
**Pull request by Affie**
Replaces and close #444

Broken testset: Broken Testset for RoME
Results:  pass:0 broken:0 fail:0 error:0
Broken Testset for RoME summary: 
  Pass:399
  Broken:6
  Fail:39
  Error:0

### CODE REVIEW

**Comment by dehann** [comment]
HI @Affie, thanks -- I'm debugging the numerical issues in IIF.  Here in RoME is a test (...913.jl) and getting the following error (stable/good on left -- current master/bad on right):
Screenshot from 2021-09-12 16-32-02


To fix this i'm walking through CSM debug steps, sure more than a few bugs will surface -- just very laborious process :-P

**Comment by Affie** [comment]
Yes, I saw that one. I couldn't figure out what was wrong and ran out of time. I would like to see the fix.

**Comment by dehann** [comment]
@Affie, I think the problem is because approxDeconv now returns tangents, where in IIF v0.24 it was assumed to be coordinates.

**Comment by dehann** [comment]
The params.useMsgLikelihoods code is creating new factors from MKD where the ProductRepr consists of a tangent rather than a point.

**Comment by dehann** [comment]
I'll open a new issue and we can work from there.

**Pull request merged**
