### PR TITLE
Parse more G2O formats and Improve PriorPose2 performance

### PR DESCRIPTION
**Pull request by Affie**

### CODE REVIEW

**Review by dehann — APPROVED** [review]

**Comment by Affie** [comment]
@dehann, what is still needed here is testing the additional g2o format features and what to do with covariances in 3d. 
Should we defer it for later and merge it as is, with a new issue to capture it?

**Comment by dehann** [comment]
Yeah, merge as is with issue detaiilng the test that is needed thanks.

**Comment by Affie** [comment]
Add tests for parseG2oInstruction

**Comment by Affie** [comment]
Fix g2o parseG2oInstruction covariance on Pose3

**Pull request merged**
