### PR TITLE
Adding projectCartesian functions

### PR DESCRIPTION
**Pull request by GearsAD**
Changes required for https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/517

### CODE REVIEW

**Comment by dehann** [comment]
Looks good to me, you can merge whenever you are ready.  I might be around for DFG v0.9.0 and IIF v0.14.0 changes but will let you know.

**Comment by GearsAD** [comment]
Cool - I just want to add the other poses and then should be good to merge.

**Comment by GearsAD** [comment]
Awaiting the DFG 0.10 tag for this.

**Comment by dehann** [comment]
Hi @GearsAD , just doing the rounds and scoping out todo's.  RoME v0.10.0 will be coming next and think we should add this PR to it.  I'll quickly add the remainder of the functions for other Variables if that saves you time.

**Comment by dehann** [comment]
waiting on #328

**Comment by dehann** [comment]
replaced by #328

**Pull request closed without merging**
